version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      GENERATE_STRUCTURES: true
      LEVEL_TYPE: FLAT
      VERSION: 1.20.1
      TYPE: FABRIC
    ports:
      - "25564:25565"
    volumes:
      # - data:/data
      - ./data:/data
      - ./mods:/mods
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
