apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: registry-server
  name: registry-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: registry-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/registry-ui-default: "true"
        io.kompose.service: registry-server
    spec:
      containers:
        - env:
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/registry.password
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials
              value: "[true]"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers
              value: "[Authorization,Accept,Cache-Control]"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods
              value: "[HEAD,GET,OPTIONS,DELETE]"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
              value: "[http://registry-ui.wayl.one]"
            - name: REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers
              value: "[Docker-Content-Digest]"
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          image: registry:2.8.2
          name: registry-server
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/registry
              name: registry
            - mountPath: /auth
              name: registry-auth
      restartPolicy: Always
      volumes:
        - name: registry
          persistentVolumeClaim:
            claimName: registry
        - name: registry-auth
          persistentVolumeClaim:
            claimName: registry-auth
status: {}
