default: convert deploy viz
convert:
    kompose convert -o deployment.yaml -n ntfy
deploy:
    kubectl apply -f deployment.yaml
viz:
    k8sviz -n ntfy --kubeconfig $KUBECONFIG -t png -o ntfy-k8s.png
restart:
    kubectl rollout restart -n ntfy deployment/ntfy
