version: "3.1"
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    # environment:
    #   - PUID=1000
    #   - PGID=1000
    # - PASSWORD=PASSWORD
    # - CUSTOM_RESULTS=false #optional
    # - DB_TYPE=sqlite #optional
    # - DB_NAME=DB_NAME #optional
    # - DB_HOSTNAME=DB_HOSTNAME #optional
    # - DB_USERNAME=DB_USERNAME #optional
    # - DB_PASSWORD=DB_PASSWORD #optional
    # - DB_PORT=DB_PORT #optional
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/data/librespeed/config:/config

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.entrypoints=http"
      - "traefik.http.routers.librespeed.rule=Host(`librespeed.${URL}`)"
      - "traefik.http.middlewares.librespeed-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.librespeed.middlewares=librespeed-https-redirect"
      - "traefik.http.routers.librespeed-secure.entrypoints=https"
      - "traefik.http.routers.librespeed-secure.rule=Host(`librespeed.local.waylonwalker.com`)"
      - "traefik.http.routers.librespeed-secure.tls=true"
      - "traefik.http.routers.librespeed-secure.service=librespeed"
      - "traefik.http.services.librespeed.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
