version: "3.1"

services:
  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    security_opt:
      - no-new-privileges:true
    ports:
      - 80
    environment:
      - TZ=UTC # optional: set desired timezone
    labels:
      kompose.service.expose: librespeed.wayl.one,librespeed.k.waylonwalker.com
