version: '3'
services:
  terraria:
    image: ryshe/terraria:latest
    command: -world /root/.local/share/Terraria/Worlds/dreamland-of-decaying-meat.wld -autocreate 3
    volumes:
      - $HOME/terraria/world:/root/.local/share/Terraria/Worlds
    ports:
      - 7777:7777
  terraria-wyatt:
    image: ryshe/terraria:latest
    command: -world /root/.local/share/Terraria/Worlds/dreamland-of-decaying-meat.wld -autocreate 3
    volumes:
      - $HOME/terraria/world-wyatt:/root/.local/share/Terraria/Worlds
    ports:
      - 7778:7777
