version: '3'

services:
  sandcrawler:
    image: minio/minio
    ports:
      - "9090:9000"
      - "9091:9001"
    volumes:
      - /mnt/vault/sandcrawler:/data
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}
