version: "3"

services:
  sandcrawler:
    image: minio/minio
    ports:
      - 9000
      - 9001
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: waylon
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

    # labels:
    #   kompose.service.expose: minio.wayl.one, minio-ui.wayl.one
    #   kompose.image-pull-secret: regcred

volumes:
  minio_storage: {}
