version: "3.1"

services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - syncthing-config:/config
      - syncthing:/data
    ports:
      - 8384
      - 22000/tcp
      - 22000/udp
      - 21027/udp
    labels:
      kompose.service.expose: syncthing.wayl.one
      #   kompose.image-pull-secret: regcred

networks:
  proxy:
    external: true

volumes:
  syncthing: {}
  syncthing-config: {}
