---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml -n installer
    kompose.image-pull-secret: regcred
    kompose.service.expose: installer.wayl.one,installer.k.waylonwalker.com,i.wayl.one,i.k.waylonwalker.com
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: installer
  name: installer
  namespace: installer
spec:
  ports:
    - name: "3003"
      port: 3003
      targetPort: 3003
  selector:
    io.kompose.service: installer
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: installer
  namespace: installer
spec: {}
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml -n installer
    kompose.image-pull-secret: regcred
    kompose.service.expose: installer.wayl.one,installer.k.waylonwalker.com,i.wayl.one,i.k.waylonwalker.com
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: installer
  name: installer
  namespace: installer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: installer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yaml -n installer
        kompose.image-pull-secret: regcred
        kompose.service.expose: installer.wayl.one,installer.k.waylonwalker.com,i.wayl.one,i.k.waylonwalker.com
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/installer-default: "true"
        io.kompose.service: installer
    spec:
      containers:
        - env:
            - name: HTTP_HOST
              value: 0.0.0.0
            - name: PORT
              value: "3003"
            - name: USER
              value: waylonwalker
          image: registry.wayl.one/installer
          name: installer
          ports:
            - containerPort: 3003
              protocol: TCP
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml -n installer
    kompose.image-pull-secret: regcred
    kompose.service.expose: installer.wayl.one,installer.k.waylonwalker.com,i.wayl.one,i.k.waylonwalker.com
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: installer
  name: installer
  namespace: installer
spec:
  rules:
    - host: installer.wayl.one
      http:
        paths:
          - backend:
              service:
                name: installer
                port:
                  number: 3003
            path: /
            pathType: Prefix
    - host: installer.k.waylonwalker.com
      http:
        paths:
          - backend:
              service:
                name: installer
                port:
                  number: 3003
            path: /
            pathType: Prefix
    - host: i.wayl.one
      http:
        paths:
          - backend:
              service:
                name: installer
                port:
                  number: 3003
            path: /
            pathType: Prefix
    - host: i.k.waylonwalker.com
      http:
        paths:
          - backend:
              service:
                name: installer
                port:
                  number: 3003
            path: /
            pathType: Prefix
status:
  loadBalancer: {}

