version: "3"

services:
  installer:
    image: registry.wayl.one/installer
    container_name: installer
    ports:
      - 3003
    environment:
      - HTTP_HOST=0.0.0.0
      - PORT=3003
      - USER=waylonwalker
      - REPO=waylonwalker.com
    labels:
      kompose.service.expose: installer.wayl.one,installer.k.waylonwalker.com,i.wayl.one,i.k.waylonwalker.com
      kompose.image-pull-secret: regcred
